/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ivory: {
          light: '#faf9f5',
          medium: '#f0eee6',
          dark: '#e8e6dc',
        },
        slate: {
          dark: '#141413',
          light: '#5e5d59',
        },
        cloud: {
          dark: '#87867f',
          medium: '#b0aea5',
        },
        oat: '#e3dacc',
      },
      fontFamily: {
        sans: ['Anthropic Sans', 'Arial', 'sans-serif'],
        serif: ['Anthropic Serif', 'Georgia', 'serif'],
        mono: ['Anthropic Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-xl': ['57.73px', { lineHeight: '63.5px', fontWeight: '700' }],
        'display-serif': ['96px', { lineHeight: '105.6px', letterSpacing: '1.6px' }],
        'body-serif-m': ['20px', { lineHeight: '28px' }],
        'body-serif-s': ['16px', { lineHeight: '22.4px' }],
        'ui-sans-m': ['16px', { lineHeight: '22.4px', letterSpacing: '-0.08px' }],
        'ui-sans-semibold': ['24px', { lineHeight: '31.2px', fontWeight: '600' }],
        'detail-xs': ['12px', { lineHeight: '16.8px', letterSpacing: '-0.24px' }],
        'serif-accent': ['26px', { lineHeight: '36.4px' }],
        caption: ['12px', { lineHeight: '16.8px', letterSpacing: '-0.24px' }],
        body: ['16px', { lineHeight: '22.4px', letterSpacing: '-0.08px' }],
        subheading: ['24px', { lineHeight: '31.2px', fontWeight: '600' }],
        'heading-sm': ['24px', { lineHeight: '31.2px', fontWeight: '600' }],
        heading: ['57.73px', { lineHeight: '63.5px', fontWeight: '700' }],
        display: ['96px', { lineHeight: '105.6px', letterSpacing: '1.6px' }],
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.5rem',
        '6': '2rem',
        '7': '2.5rem',
        '8': '3rem',
        '9': '4rem',
        'gutter': '2rem',
        'site-margin': '64px',
        'section-sm': '4rem',
        'section-main': '10rem',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.5rem',
        lg: '1rem',
        xl: '1rem',
        '2xl': '1rem',
        '3xl': '1rem',
        full: '100vw',
      },
      maxWidth: {
        site: 'calc(100% - (2 * var(--site-margin)))',
      },
      width: {
        sidebar: '18rem',
        'sidebar-collapsed': '5rem',
        'search-bar': '16rem',
        'search-bar-lg': '24rem',
        'control-icon': '2.5rem',
        action: 'var(--action-size)',
        'action-icon': 'var(--action-icon-size)',
        'avatar-sm': '2rem',
        'avatar-md': '2.5rem',
        'avatar-lg': '3rem',
        'avatar-xl': '4rem',
      },
      height: {
        'control-sm': '2rem',
        'control-md': '2.5rem',
        'control-lg': '3rem',
        'control-icon': '2.5rem',
        action: 'var(--action-size)',
        'action-icon': 'var(--action-icon-size)',
        'avatar-sm': '2rem',
        'avatar-md': '2.5rem',
        'avatar-lg': '3rem',
        'avatar-xl': '4rem',
        header: '4rem',
      },
      minHeight: {
        'control-sm': '2rem',
        'control-md': '2.5rem',
        'control-lg': '3rem',
        header: '4rem',
        action: 'var(--action-size)',
      },
      maxHeight: {
        'panel-sm': '12rem',
        'panel-md': '16rem',
      },
      minWidth: {
        action: 'var(--action-size)',
      },
      screens: {
        tablet: '768px',
        desktop: '992px',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
