FROM redis:7-alpine

COPY scripts/redis-docker-entrypoint.sh /redis-entrypoint.sh
COPY infra/redis/redis.conf /usr/local/etc/redis/redis.conf

RUN chmod +x /redis-entrypoint.sh

ENTRYPOINT ["/bin/sh", "/redis-entrypoint.sh"]
CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
