import type { ArtPromptRecipe } from './art-prompt.types';

/**
 * Curated MeiGen-style art prompt recipes for social post visuals.
 * Templates use {{slot}} placeholders filled from brand kit + post copy.
 */
export const ART_PROMPT_RECIPES: ArtPromptRecipe[] = [
  {
    id: 'infographic-technical-001',
    family: 'infographic-technical',
    name: 'Technical Infographic',
    description: 'Clean technical diagram with labeled nodes and data flow arrows.',
    template:
      'Technical infographic for {{productName}}, {{subject}}. Isometric nodes, thin connector lines, {{primaryColor}} accent on dark slate background. Minimal labels, no paragraph text. {{style}} SaaS aesthetic, 4K.',
    slots: ['productName', 'subject', 'primaryColor', 'style'],
    intents: ['educate', 'data', 'tips'],
    industries: ['saas', 'tech', 'fintech', 'logistics'],
    formats: ['1:1', '4:5'],
    platforms: ['linkedin', 'instagram', 'twitter'],
    carouselRoles: ['feature', 'step'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 90,
    meigenRank: 1,
  },
  {
    id: 'infographic-educational-012',
    family: 'infographic-educational',
    name: 'Educational Steps',
    description: 'Numbered step infographic with icons and short labels.',
    template:
      'Educational step-by-step infographic: {{subject}} for {{audience}}. 3-5 numbered icons, {{primaryColor}} and white, flat vector style. Clear hierarchy, legible short labels only. Instagram-ready.',
    slots: ['subject', 'audience', 'primaryColor'],
    intents: ['educate', 'tips'],
    industries: ['saas', 'health', 'education', 'general'],
    formats: ['1:1', '4:5'],
    platforms: ['instagram', 'linkedin', 'facebook'],
    carouselRoles: ['hook', 'step', 'cta'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 88,
    meigenRank: 12,
  },
  {
    id: 'product-hero-json-050',
    family: 'product-hero',
    name: 'Product Hero Spotlight',
    description: 'Hero product shot with dramatic lighting and brand color glow.',
    template:
      'Hero product visual for {{productName}}: {{subject}}. Centered product mockup, soft studio lighting, {{primaryColor}} rim light, subtle gradient backdrop. Premium {{style}} marketing photo, no UI chrome.',
    slots: ['productName', 'subject', 'primaryColor', 'style'],
    intents: ['promote', 'product', 'announce'],
    industries: ['saas', 'ecommerce', 'tech', 'general'],
    formats: ['1:1', '4:5', '9:16'],
    platforms: ['instagram', 'linkedin', 'tiktok', 'facebook'],
    carouselRoles: ['hook'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 95,
    meigenRank: 50,
  },
  {
    id: 'poster-social-4x5-014',
    family: 'poster-social',
    name: 'Social Poster 4:5',
    description: 'Bold typographic poster optimized for Instagram feed 4:5.',
    template:
      'Social media poster 4:5 for {{productName}}. Headline concept: "{{headline}}". Bold sans-serif typography, {{primaryColor}} on deep neutral background. Minimal layout, high contrast, editorial poster design.',
    slots: ['productName', 'headline', 'primaryColor'],
    intents: ['announce', 'promote', 'inspire'],
    industries: ['general', 'saas', 'retail', 'events'],
    formats: ['4:5'],
    platforms: ['instagram', 'facebook'],
    carouselRoles: ['hook', 'cta'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 85,
    meigenRank: 14,
  },
  {
    id: 'carousel-dtc-037',
    family: 'carousel-dtc',
    name: 'DTC Carousel Cover',
    description: 'Direct-to-consumer carousel opener with lifestyle + product.',
    template:
      'DTC carousel cover slide: {{subject}} by {{productName}}. Lifestyle context, product in hand, warm natural light, {{style}} aesthetic. Leave lower third clean for text overlay. {{primaryColor}} accent props.',
    slots: ['subject', 'productName', 'style', 'primaryColor'],
    intents: ['promote', 'story', 'product'],
    industries: ['ecommerce', 'beauty', 'food', 'retail'],
    formats: ['1:1', '4:5'],
    platforms: ['instagram', 'facebook'],
    carouselRoles: ['hook'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 87,
    meigenRank: 37,
  },
  {
    id: 'logo-fluid-230',
    family: 'logo-fluid',
    name: 'Fluid Brand Mark',
    description: 'Abstract fluid logo-inspired brand visual without literal logo.',
    template:
      'Abstract fluid brand visual inspired by {{productName}} identity. Liquid metal shapes in {{primaryColor}} and {{secondaryColor}}, dark background, premium motion-blur feel. No text, no literal logo — brand essence only.',
    slots: ['productName', 'primaryColor', 'secondaryColor'],
    intents: ['brand', 'inspire'],
    industries: ['saas', 'tech', 'luxury', 'general'],
    formats: ['1:1', '9:16'],
    platforms: ['instagram', 'linkedin', 'tiktok'],
    carouselRoles: ['hook'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 75,
    meigenRank: 230,
  },
  {
    id: 'illustration-editorial-045',
    family: 'illustration-editorial',
    name: 'Editorial Illustration',
    description: 'Editorial spot illustration with narrative scene.',
    template:
      'Editorial illustration: {{subject}} for {{productName}}. Flat color blocks, limited palette {{primaryColor}} {{secondaryColor}}, magazine editorial style. Human figures optional, diverse, professional context. No speech bubbles.',
    slots: ['subject', 'productName', 'primaryColor', 'secondaryColor'],
    intents: ['educate', 'inspire', 'story'],
    industries: ['saas', 'health', 'education', 'general'],
    formats: ['1:1', '4:5'],
    platforms: ['linkedin', 'instagram', 'twitter'],
    carouselRoles: ['feature', 'step'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 82,
    meigenRank: 45,
  },
  {
    id: 'flatlay-instagram-051',
    family: 'flatlay',
    name: 'Instagram Flatlay',
    description: 'Top-down flatlay with props and brand-colored accents.',
    template:
      'Instagram flatlay for {{productName}}: {{subject}}. Top-down composition, marble or linen surface, {{primaryColor}} accent objects, soft shadows. Aspirational {{style}} lifestyle, no faces, no text.',
    slots: ['productName', 'subject', 'primaryColor', 'style'],
    intents: ['promote', 'inspire', 'product'],
    industries: ['ecommerce', 'beauty', 'food', 'retail'],
    formats: ['1:1', '4:5'],
    platforms: ['instagram', 'facebook'],
    carouselRoles: ['hook', 'feature'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 80,
    meigenRank: 51,
  },
  {
    id: 'brand-vi-matrix-006',
    family: 'brand-vi',
    name: 'Brand VI Matrix',
    description: 'Visual identity grid showing color, pattern, and texture system.',
    template:
      'Brand visual identity matrix for {{productName}}. Grid of color swatches {{primaryColor}} {{secondaryColor}}, geometric patterns, texture samples. Swiss design grid, minimal labels. Corporate brand guidelines aesthetic.',
    slots: ['productName', 'primaryColor', 'secondaryColor'],
    intents: ['brand', 'announce'],
    industries: ['saas', 'tech', 'agency', 'general'],
    formats: ['1:1', '4:5'],
    platforms: ['linkedin', 'instagram'],
    carouselRoles: ['feature'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 70,
    meigenRank: 6,
  },
  {
    id: 'travel-portal-041',
    family: 'travel-portal',
    name: 'Travel Portal Scene',
    description: 'Immersive destination portal with depth and golden hour light.',
    template:
      'Immersive travel portal scene: {{subject}}. Wide cinematic vista through arched frame, golden hour, depth layers, {{style}} color grading. Sense of discovery and aspiration. No text overlays.',
    slots: ['subject', 'style'],
    intents: ['inspire', 'story'],
    industries: ['travel', 'hospitality', 'general'],
    formats: ['4:5', '9:16'],
    platforms: ['instagram', 'tiktok', 'facebook'],
    carouselRoles: ['hook'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 78,
    meigenRank: 41,
  },
  {
    id: 'poster-food-instagram-100',
    family: 'poster-food',
    name: 'Food Instagram Poster',
    description: 'Appetizing food poster with vibrant colors and texture.',
    template:
      'Food poster for {{subject}}. Close-up hero dish, steam and texture detail, vibrant {{primaryColor}} props, dark moody background. Instagram food photography, appetizing, no text or logos.',
    slots: ['subject', 'primaryColor'],
    intents: ['promote', 'inspire'],
    industries: ['food', 'hospitality', 'retail'],
    formats: ['1:1', '4:5'],
    platforms: ['instagram', 'facebook'],
    carouselRoles: ['hook'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 83,
    meigenRank: 100,
  },
  {
    id: 'poster-editorial-475',
    family: 'poster-editorial',
    name: 'Editorial Quote Poster',
    description: 'High-fashion editorial poster with strong typography zone.',
    template:
      'Editorial poster design for {{productName}}. Concept: "{{headline}}". High-fashion layout, generous whitespace, {{primaryColor}} accent line, serif + sans pairing zone. Luxury {{style}} magazine cover feel.',
    slots: ['productName', 'headline', 'primaryColor', 'style'],
    intents: ['inspire', 'announce', 'brand'],
    industries: ['luxury', 'fashion', 'saas', 'general'],
    formats: ['4:5', '9:16'],
    platforms: ['instagram', 'linkedin'],
    carouselRoles: ['hook', 'cta'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 84,
    meigenRank: 475,
  },
  {
    id: 'stat-highlight-data-022',
    family: 'stat-highlight',
    name: 'Stat Highlight',
    description: 'Large numeric stat with supporting visual metaphor.',
    template:
      'Data visualization poster: key insight about {{subject}} for {{audience}}. One dominant number area, {{primaryColor}} gradient, abstract chart metaphor, clean minimal design. LinkedIn-ready infographic.',
    slots: ['subject', 'audience', 'primaryColor'],
    intents: ['data', 'educate'],
    industries: ['saas', 'fintech', 'analytics', 'general'],
    formats: ['1:1', '4:5'],
    platforms: ['linkedin', 'twitter', 'instagram'],
    carouselRoles: ['feature', 'hook'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 86,
    meigenRank: 22,
  },
  {
    id: 'quote-insight-minimal-018',
    family: 'quote-insight',
    name: 'Quote Insight Minimal',
    description: 'Minimal quote card with abstract background texture.',
    template:
      'Minimal quote card background for {{productName}}. Soft abstract texture in {{primaryColor}} tones, subtle grain, center safe zone for text. Calm professional mood, {{style}} aesthetic.',
    slots: ['productName', 'primaryColor', 'style'],
    intents: ['inspire', 'educate'],
    industries: ['general', 'saas', 'coaching'],
    formats: ['1:1', '4:5'],
    platforms: ['linkedin', 'instagram', 'twitter'],
    carouselRoles: ['hook', 'feature'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 79,
    meigenRank: 18,
  },
  {
    id: 'tip-card-gradient-033',
    family: 'tip-card',
    name: 'Tip Card Gradient',
    description: 'Gradient tip card with icon area and clean layout.',
    template:
      'Social tip card visual: {{subject}}. Smooth gradient {{primaryColor}} to {{secondaryColor}}, subtle geometric shapes, space for icon and short tip text. Modern {{style}} UI marketing card.',
    slots: ['subject', 'primaryColor', 'secondaryColor', 'style'],
    intents: ['tips', 'educate'],
    industries: ['saas', 'tech', 'general'],
    formats: ['1:1', '4:5'],
    platforms: ['instagram', 'linkedin', 'facebook'],
    carouselRoles: ['step', 'feature'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 81,
    meigenRank: 33,
  },
  {
    id: 'promo-cta-bold-029',
    family: 'promo-cta',
    name: 'Promo CTA Bold',
    description: 'High-energy promo visual with CTA-focused composition.',
    template:
      'Promotional social visual for {{productName}}: {{goal}}. Dynamic angle, bold {{primaryColor}} energy burst, product hero zone, urgency without clutter. Performance ad creative, {{style}} style.',
    slots: ['productName', 'goal', 'primaryColor', 'style'],
    intents: ['promote', 'announce'],
    industries: ['ecommerce', 'saas', 'retail', 'general'],
    formats: ['1:1', '4:5', '9:16'],
    platforms: ['instagram', 'facebook', 'tiktok'],
    carouselRoles: ['cta', 'hook'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 88,
    meigenRank: 29,
  },
  {
    id: 'story-vertical-reel-055',
    family: 'story-vertical',
    name: 'Story Vertical Reel',
    description: 'Full-bleed vertical scene for Stories/Reels background.',
    template:
      'Vertical 9:16 story background for {{productName}}: {{visualDescription}}. Full-bleed cinematic scene, upper 60% visual interest, lower area darker for text overlay. {{platform}} Reels aesthetic, {{style}}.',
    slots: ['productName', 'visualDescription', 'platform', 'style'],
    intents: ['story', 'promote', 'inspire'],
    industries: ['general', 'saas', 'ecommerce'],
    formats: ['9:16'],
    platforms: ['instagram', 'tiktok', 'facebook'],
    carouselRoles: [],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 92,
    meigenRank: 55,
  },
  {
    id: 'comparison-split-067',
    family: 'comparison',
    name: 'Before/After Split',
    description: 'Split-screen before/after comparison visual.',
    template:
      'Before and after split comparison: {{subject}}. Left side muted/desaturated problem state, right side vibrant {{primaryColor}} solution state. Clean vertical divider, no text labels, conceptual metaphor.',
    slots: ['subject', 'primaryColor'],
    intents: ['compare', 'educate', 'promote'],
    industries: ['saas', 'health', 'beauty', 'general'],
    formats: ['1:1', '4:5'],
    platforms: ['instagram', 'linkedin', 'facebook'],
    carouselRoles: ['hook', 'feature'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 77,
    meigenRank: 67,
  },
  {
    id: 'saas-dashboard-abstract-073',
    family: 'saas-abstract',
    name: 'SaaS Dashboard Abstract',
    description: 'Abstract UI/dashboard visualization without readable text.',
    template:
      'Abstract SaaS dashboard visualization for {{productName}}: {{subject}}. Floating glass panels, {{primaryColor}} data viz shapes, dark mode, depth blur. No readable UI text, conceptual product screenshot feel.',
    slots: ['productName', 'subject', 'primaryColor'],
    intents: ['product', 'educate', 'data'],
    industries: ['saas', 'fintech', 'tech'],
    formats: ['1:1', '4:5', '9:16'],
    platforms: ['linkedin', 'instagram', 'twitter'],
    carouselRoles: ['feature', 'step'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 89,
    meigenRank: 73,
  },
  {
    id: 'event-announcement-088',
    family: 'event',
    name: 'Event Announcement',
    description: 'Event promo with dynamic lighting and stage energy.',
    template:
      'Event announcement visual for {{subject}} by {{productName}}. Stage lighting, crowd energy bokeh, {{primaryColor}} spotlights, excitement and urgency. Wide cinematic crop, space for event title overlay.',
    slots: ['subject', 'productName', 'primaryColor'],
    intents: ['announce', 'promote'],
    industries: ['events', 'saas', 'general'],
    formats: ['1:1', '4:5', '9:16'],
    platforms: ['instagram', 'linkedin', 'facebook'],
    carouselRoles: ['hook'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 76,
    meigenRank: 88,
  },
  {
    id: 'testimonial-moment-091',
    family: 'testimonial',
    name: 'Testimonial Moment',
    description: 'Authentic customer success moment, candid professional.',
    template:
      'Authentic customer success moment for {{productName}}: {{subject}}. Candid professional setting, natural smile, soft window light, {{style}} brand colors in environment. Trustworthy, not stock-photo sterile.',
    slots: ['productName', 'subject', 'style'],
    intents: ['inspire', 'promote', 'story'],
    industries: ['saas', 'coaching', 'general'],
    formats: ['1:1', '4:5'],
    platforms: ['linkedin', 'instagram', 'facebook'],
    carouselRoles: ['feature'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 74,
    meigenRank: 91,
  },
  {
    id: 'luxury-gradient-105',
    family: 'luxury',
    name: 'Luxury Gradient',
    description: 'Premium luxury gradient with subtle texture and gold accents.',
    template:
      'Luxury brand visual for {{productName}}. Deep charcoal to {{primaryColor}} gradient, subtle gold foil texture, premium minimal composition. High-end {{style}} aesthetic, no product, pure brand mood.',
    slots: ['productName', 'primaryColor', 'style'],
    intents: ['brand', 'inspire'],
    industries: ['luxury', 'fintech', 'saas'],
    formats: ['1:1', '4:5', '9:16'],
    platforms: ['instagram', 'linkedin'],
    carouselRoles: ['hook'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 72,
    meigenRank: 105,
  },
  {
    id: 'playful-emoji-scene-112',
    family: 'playful',
    name: 'Playful 3D Scene',
    description: 'Playful 3D rendered scene with soft clay materials.',
    template:
      'Playful 3D clay render: {{subject}} for {{productName}}. Soft rounded shapes, pastel {{primaryColor}} and white, studio lighting, friendly approachable mood. Social media playful aesthetic.',
    slots: ['subject', 'productName', 'primaryColor'],
    intents: ['tips', 'educate', 'inspire'],
    industries: ['education', 'saas', 'general'],
    formats: ['1:1', '4:5'],
    platforms: ['instagram', 'tiktok', 'facebook'],
    carouselRoles: ['hook', 'step'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 73,
    meigenRank: 112,
  },
  {
    id: 'linkedin-thought-leadership-119',
    family: 'thought-leadership',
    name: 'Thought Leadership',
    description: 'Professional thought-leadership visual with abstract network.',
    template:
      'Thought leadership visual for {{subject}}. Abstract network nodes, professional blue-grey palette with {{primaryColor}} accent, clean corporate aesthetic. LinkedIn banner quality, minimal and authoritative.',
    slots: ['subject', 'primaryColor'],
    intents: ['educate', 'inspire', 'data'],
    industries: ['saas', 'consulting', 'fintech'],
    formats: ['1:1', '4:5'],
    platforms: ['linkedin', 'twitter'],
    carouselRoles: ['hook', 'feature'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 85,
    meigenRank: 119,
  },
  {
    id: 'tiktok-trend-vertical-125',
    family: 'tiktok-trend',
    name: 'TikTok Trend Vertical',
    description: 'Trendy vertical visual with bold color blocks and energy.',
    template:
      'TikTok trend vertical visual: {{subject}} for {{productName}}. Bold color blocks {{primaryColor}}, dynamic diagonal composition, Gen-Z energy, 9:16 full frame. Eye-catching hook frame, no text.',
    slots: ['subject', 'productName', 'primaryColor'],
    intents: ['promote', 'story', 'tips'],
    industries: ['general', 'ecommerce', 'saas'],
    formats: ['9:16'],
    platforms: ['tiktok', 'instagram'],
    carouselRoles: ['hook'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 90,
    meigenRank: 125,
  },
  {
    id: 'carousel-listicle-131',
    family: 'carousel-listicle',
    name: 'Carousel Listicle Slide',
    description: 'Listicle carousel slide with numbered visual hierarchy.',
    template:
      'Carousel listicle slide: tip about {{subject}} for {{audience}}. Number badge area, {{primaryColor}} accent, clean card layout on soft neutral background. One idea per slide, {{style}} design system.',
    slots: ['subject', 'audience', 'primaryColor', 'style'],
    intents: ['tips', 'educate'],
    industries: ['general', 'saas', 'health'],
    formats: ['1:1', '4:5'],
    platforms: ['instagram', 'linkedin'],
    carouselRoles: ['step', 'feature'],
    typographyInImage: true,
    requiresReferenceImage: false,
    priority: 84,
    meigenRank: 131,
  },
  {
    id: 'fintech-trust-138',
    family: 'fintech',
    name: 'Fintech Trust',
    description: 'Secure, trustworthy fintech visual with geometric shields.',
    template:
      'Fintech trust visual for {{productName}}: {{subject}}. Geometric shield motifs, {{primaryColor}} and navy, secure professional mood. Abstract finance symbols, no readable numbers, premium banking aesthetic.',
    slots: ['productName', 'subject', 'primaryColor'],
    intents: ['promote', 'educate', 'data'],
    industries: ['fintech', 'saas'],
    formats: ['1:1', '4:5'],
    platforms: ['linkedin', 'instagram', 'twitter'],
    carouselRoles: ['hook', 'feature'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 87,
    meigenRank: 138,
  },
  {
    id: 'health-wellness-calm-145',
    family: 'health',
    name: 'Health Wellness Calm',
    description: 'Calming wellness scene with natural elements.',
    template:
      'Wellness visual: {{subject}} for {{audience}}. Soft natural light, plants, calm {{primaryColor}} tones, serene spa-like atmosphere. Health and balance mood, no medical imagery, aspirational.',
    slots: ['subject', 'audience', 'primaryColor'],
    intents: ['inspire', 'educate', 'tips'],
    industries: ['health', 'coaching', 'general'],
    formats: ['1:1', '4:5', '9:16'],
    platforms: ['instagram', 'facebook', 'tiktok'],
    carouselRoles: ['hook', 'feature'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 78,
    meigenRank: 145,
  },
  {
    id: 'agency-portfolio-152',
    family: 'agency',
    name: 'Agency Portfolio',
    description: 'Creative agency portfolio piece with bold geometry.',
    template:
      'Creative agency portfolio visual for {{productName}}: {{subject}}. Bold geometric composition, {{primaryColor}} {{secondaryColor}} contrast, avant-garde layout. Design studio showcase quality, experimental but polished.',
    slots: ['productName', 'subject', 'primaryColor', 'secondaryColor'],
    intents: ['brand', 'inspire', 'announce'],
    industries: ['agency', 'general', 'saas'],
    formats: ['1:1', '4:5'],
    platforms: ['instagram', 'linkedin'],
    carouselRoles: ['hook'],
    typographyInImage: false,
    requiresReferenceImage: false,
    priority: 71,
    meigenRank: 152,
  },
];

export function getArtPromptRecipeById(id: string): ArtPromptRecipe | undefined {
  return ART_PROMPT_RECIPES.find((recipe) => recipe.id === id);
}
